on:
  push:
    paths:
      - '**.Rmd'
name: Render-rmd

jobs:
  build:
    runs-on: macOS-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup R
        uses: r-lib/actions/setup-r@v1

      - name: Install pandoc
        uses: r-lib/actions/setup-pandoc@v1

      - name: Cache Renv packages
        uses: actions/cache@v2
        with:
          path: $HOME/.local/share/renv
          key: r-${{ hashFiles('renv.lock') }}
          restore-keys: r-

      - name: Install packages
        run: |
          R -e 'install.packages(c("renv", "rmarkdown", "remotes", "vcr"))'
          R -e 'remotes::install_github("mps9506/rATTAINS")'
          R -e 'renv::restore()'

      - name: Render Rmarkdown files
        run: |
          R -e 'rmarkdown::render("README.Rmd")'
          R -e 'rmarkdown::render("vignettes/Introduction.Rmd")'

      - name: Commit results
        run: |
          git config --local user.name "$GITHUB_ACTOR"
          git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git add README.md vignettes/Introduction.html
          git commit -m 'Re-build Rmarkdown files' || echo "No changes to commit"
          git push origin || echo "No changes to commit"
